### ISSUE TITLE
Sutom doesn't let to choose the port to listen on

### ISSUE THREAD

**Issue by fflorent** [YunoHost-Apps/sutom_ynh#5]
NB: This is not an issue of this package per se, just a ticket to track the resolution.

## The problem

On my server, the port 4000 is already bound. Yunohost therefore choose another one (4001), which is the expected behavior.

However, Sutom does not let the choice to customize the port:
https://framagit.org/JonathanMM/sutom/-/blob/335b42256fbbe5080d7756fc0ca085433c9d14f5/ts/server.ts#L6

## What to do

The only solution would be to ask a change to the project or to do it by our own.

I'll open a PR to the SUTOM project so we can override the default port by a environment variable. Therefore in the Yunohost package, we would then have to set this environment variable in the systemd service.

**Comment by tituspijean** [comment]
To be actually tested, but I guess patching the line you quoted and running `nom install` should do the trick.

**Comment by fflorent** [comment]
It should do.

But the PR is already open, let's see whether the author will be reactive:
https://framagit.org/JonathanMM/sutom/-/merge_requests/8

If not, we'll see to patch it

**Comment by fflorent** [comment]
Should be fixed in last testing update:
https://github.com/YunoHost-Apps/sutom_ynh/pull/4

**Comment by ericgaspar** [comment]
With #4 I have the following error (that prevents the grid to be loaded)
No idea on how to fix it


```
Feb 07 17:34:43 systemd[1]: Started Sutom: online word game.
Feb 07 17:34:44 npm[298475]: > sutom@1.0.0 start
Feb 07 17:34:44 npm[298475]: > tsc && node js/server.js
Feb 07 17:35:04 npm[298557]: Jeu démarré : http://localhost:4000
Feb 07 17:35:04 npm[298557]: [Error: ENOENT: no such file or directory, open 'mots/31.txt'] {
Feb 07 17:35:04 npm[298557]:   errno: -2,
Feb 07 17:35:04 npm[298557]:   code: 'ENOENT',
Feb 07 17:35:04 npm[298557]:   syscall: 'open',
Feb 07 17:35:04 npm[298557]:   path: 'mots/31.txt'
Feb 07 17:35:04 npm[298557]: }
```

**Comment by fflorent** [comment]
That's something I am investigating… It seems there are some tools to help generating these words (in the `utils/` directory), though I don't how to use them.

I wonder if the author don't let us generate a list of words by our own, but that's not very practical for self-hosting…

**Comment by yalh76** [comment]
should be fixed for now, with the SUTOM_PORT in the service
