### ISSUE TITLE
The End of Sutom

### ISSUE THREAD

**Issue by Tagadda** [YunoHost-Apps/sutom_ynh#7]
Soo France Television asked Sutom to change the name, and Sutom decided to stop.
[See on Twitter](https://twitter.com/Jonamaths/status/1506899535947345921)
The gitlab repo will be deleted so we need to use another one.

**Comment by stilobique** [comment]
Hum, some fork have been available with an another name ?

**Comment by Tagadda** [comment]
I forked [here](https://github.com/Tagadda/SUTOM), without changing the name.

**Comment by tituspijean** [comment]
The end, or not?

[Twitter update](https://mobile.twitter.com/Jonamaths/status/1506994441868951553https://mobile.twitter.com/Jonamaths/status/1506994441868951553)

**Comment by ericgaspar** [comment]
I propose to delete this repo all together because it does not work without upstream I believe...

**Comment by Tagadda** [comment]
Look like the project will not die, France Television seems to have change position.
